name: Release

on:
  push:
    tags:
    - 'v*'
    - 'test-v*'
  workflow_dispatch:
    inputs:
      name:
        description: 'Why?'
        required: true
        default: 'Testing a new release'

env:
  GO111MODULE: on

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger OBS services
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_type: 'form-urlencoded'
        webhook_url: ${{ secrets.OBS_WEBHOOK_URL }}
        webhook_secret: ${{ secrets.OBS_WEBHOOK_TOKEN }}
 
