name: Release

on:
  push:
    tags:
    - 'v*'
    - 'test-v*'

env:
  GO111MODULE: on

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger OBS services
      uses: distributhor/workflow-webhook@v2
      if: ${{ startsWith(matrix.os, 'ubuntu-') && github.ref_name == 'main' }}
      env:
        webhook_type: 'form-urlencoded'
        webhook_url: ${{ secrets.OBS_WEBHOOK_URL }}
        webhook_secret: ${{ secrets.OBS_WEBHOOK_TOKEN }}
 
